-- Migration 003: Seed all 88 Rally KPIs
-- Run AFTER 001_initial_schema.sql and 002_kpi_schema_update.sql

INSERT INTO public.kpis
  (code, name, description, kpi_status, unit, aggregation_method, tags, impact_pathway)
VALUES

('RA1',
 'Affordable housing units created, renovated or preserved (#)',
 'The total number of affordable housing units that were newly constructed, renovated, or preserved during the reporting period. Includes units added through new construction or acquisition; units maintained or improved through renovation; and existing units preserved as affordable (e.g., via non-profit or community ownership, financing arrangements, or rent supplements). Units must meet established affordability thresholds, such as rents set at or below a defined percentage of market rates or household income (e.g., 80% of median market rent, or no more than 30% of gross income). Includes both general and supportive housing.',
 'Validated', 'Housing units', 'Sum',
 ARRAY['Affordable Housing'], 'Output'),

('RA45',
 'Affordable housing units financed (units)',
 'This indicator tracks the total number of affordable housing units that received financial support — such as loans, grants, or equity investments — during the reporting period. It reflects the scope of financial commitments made to develop, preserve, or renovate housing that meets affordability criteria, even if construction or renovation has not yet been completed.',
 'Validated', 'Housing units', 'Sum',
 ARRAY['Affordable Housing'], 'Output'),

('RA80',
 'Air pollutants avoided (Tonnes)',
 'The total estimated mass of air pollutants avoided during the reporting period as a result of a company''s products or services, calculated as the sum of avoided emissions of key pollutants such as NOx, PM2.5, and SO2 relative to a baseline scenario.',
 'Needs Follow-Up', 'Tonnes', 'Sum',
 ARRAY['Clean Air', 'Pollution Prevention'], 'Outcome'),

('RA47',
 'Arts and culture products and services sold (#)',
 'This indicator captures the total number of cultural products and services sold or delivered through supported initiatives, platforms, or programs. It reflects the commercialization and dissemination of creative works (e.g., visual art) and the delivery of community-based cultural experiences (e.g., arts education or extracurricular programs).',
 'Validated', 'Cultural products/services', 'Sum',
 ARRAY['Arts and Culture'], 'Output'),

('RA49',
 'Capital deployed to social purpose organizations (CAD)',
 'Measures the total dollar amount of financing or investment capital deployed to non-profits, charities, and social enterprises operating in underserved capital markets. This includes funds directed toward strengthening community infrastructure, enabling revenue generation, and supporting the growth and sustainability of organizations that advance social and economic impact.',
 'Validated', 'CAD', 'Sum',
 ARRAY['Financial Inclusion'], 'Output'),

('RA52',
 'Capital invested in affordable housing (CAD)',
 'The total gross value of capital committed or deployed — through debt, equity, or other financial instruments — toward affordable housing projects during the reporting period, expressed in Canadian dollars (CAD). This includes investments supporting the development, preservation, or renovation of housing that meets defined affordability criteria.',
 'Validated', 'CAD', 'Sum',
 ARRAY['Affordable Housing'], 'Output'),

('RA59',
 'CEO : median employee compensation ratio',
 'The ratio of total annual compensation of the Chief Executive Officer (CEO) to the median annual compensation of all employees during the reporting period. This may be reported directly or calculated as CEO total compensation divided by median employee compensation.',
 'Draft', 'Businesses', 'Sum',
 ARRAY['Quality Jobs'], 'Output'),

('RA31',
 'Clean energy capacity (MW)',
 'The total capacity (in megawatts) of clean energy infrastructure that is installed, under construction, or actively supported by the organization. This includes renewable energy sources such as solar, wind, hydro, green hydrogen, and other low-carbon technologies designed to reduce greenhouse gas emissions and dependence on fossil fuels.',
 'Validated', 'MW', 'Sum',
 ARRAY['Clean Energy'], 'Output'),

('RA2',
 'Clean energy capacity additions (MW)',
 'The total amount of new clean energy generation capacity added, measured in megawatts (MW). This includes capacity from renewable energy sources such as solar, wind, hydro, and green hydrogen that was either installed or supported by the organization during the reporting period.',
 'Validated', 'MW', 'Sum',
 ARRAY['Clean Energy'], 'Output'),

('RA3',
 'Clean energy generated (MWh)',
 'The amount of clean or renewable energy produced by the organization''s infrastructure during the reporting period, measured in megawatt-hours (MWh). Includes generation from solar, wind, hydro or other renewable sources.',
 'Validated', 'MWh', 'Sum',
 ARRAY['Clean Energy'], 'Output'),

('RA4',
 'Clean energy used (MWh)',
 'The amount of renewable energy consumed by the organization during the reporting period, measured in megawatt-hours (MWh). This includes electricity or heat generated and used from renewable sources such as solar, wind, hydro, or biomass.',
 'Validated', 'MWh', 'Sum',
 ARRAY['Clean Energy'], 'Output'),

('RA5',
 'Climate financing provided (CAD)',
 'The total dollar amount of financing allocated to projects or initiatives that contribute to climate adaptation and resilience. This includes investments directed to climate-vulnerable communities and infrastructure supporting environmental resilience.',
 'Validated', 'CAD', 'Sum',
 ARRAY['Climate Adaptation and Resilience'], 'Output'),

('RA86',
 'Conventional material production avoided (tonnes)',
 'An estimated value of conventional material production avoided by the company''s products and services. It is calculated using reported data, scientific facts and/or a defined theory of change for specific products and services.',
 'Validated', 'Tonnes', 'Sum',
 ARRAY['Waste Management & Circularity'], 'Output'),

('RA54',
 'Customers of financial institutions at year end (Customers)',
 'The total number of active customers of the financial institution at the end of the reporting period, including both individual and business clients who maintain accounts or financial relationships with it.',
 'Validated', 'Customers', 'Sum',
 ARRAY['Financial Inclusion'], 'Output'),

('RA74',
 'Distance travelled using low-emissions transport modes (km)',
 'An estimated value of distance travelled with a low-emissions transport mode enabled by the company''s products and services.',
 'Needs Follow-Up', 'Businesses', 'Sum',
 ARRAY['Climate Change Mitigation'], 'Output'),

('RA37',
 'Diverse customers served (#)',
 'This indicator counts the number of customers or clients that portfolio companies identify as belonging to one or more equity-deserving groups. Customers may include both B2B and B2C clients, depending on the nature of the portfolio company''s activities. For example, a company may report the number of diverse-owned businesses it sells to, or the number of diverse individuals who directly use its services or products.',
 'Validated', 'Customers', 'Sum',
 ARRAY['Racial Equity'], 'Output'),

('RA40',
 'Donations to communities and equity-deserving groups (CAD)',
 'This indicator tracks the total value of donations — both financial and in-kind — made by portfolio companies to communities, equity-deserving groups, nonprofit organizations, or community-led initiatives during the reporting period. It reflects the organization''s contribution to community well-being, social equity, and support for initiatives beyond direct commercial activities: cash contributions to charities, nonprofits, or community organizations; in-kind donations (e.g., equipment, services, food, volunteer hours, space); donations supporting racial equity, gender equity, reconciliation, or poverty alleviation efforts.',
 'Validated', 'CAD', 'Sum',
 ARRAY['Racial Equity'], 'Output'),

('RA8',
 'Education products or services provided (#)',
 'The total number of educational products or services delivered by the organization, including formal training, mentorship, learning platforms, and engagements targeting students, professionals, or educators.',
 'Validated', 'Services', 'Sum',
 ARRAY['Quality Education', 'Quality Jobs'], 'Output'),

('RA10',
 'Energy conserved (MWh)',
 'The amount of energy saved due to the organization''s products, services, or operations, measured in megawatt-hours (MWh). This includes energy efficiency, reductions in consumption, and avoided fuel use through process improvements or clean technologies.',
 'Validated', 'MWh', 'Sum',
 ARRAY['Energy Efficiency', 'Green Buildings'], 'Outcome'),

('RA88',
 'Energy savings from products or services sold (MWh)',
 'Energy savings from products or services sold (MWh).',
 'Validated', 'MWh', 'Sum',
 ARRAY['Clean Energy', 'Climate Change Mitigation'], 'Output'),

('RA11',
 'Facilities engaged in improving access to and quality of health care services (#)',
 'The number of healthcare-related facilities such as clinics, hospitals, individual practitioners or digital health partners engaged through the organization''s products or partnerships to enhance access to or quality of care.',
 'Validated', 'Healthcare facilities', 'Sum',
 ARRAY['Quality Health Care'], 'Output'),

('RA60',
 'Female representation on boards (% of board members)',
 'The percentage of board members who identify as female during the reporting period, calculated as: (Number of female board members / Total number of board members) x 100.',
 'Draft', 'Businesses', 'Sum',
 ARRAY['Quality Jobs'], 'Output'),

('RA12',
 'Financial inclusion products or services (#)',
 'The number of financial inclusion products or services delivered by the organization, such as credit, insurance, savings tools, or digital financial platforms that enable access for historically excluded or underserved populations. This includes offerings such as credit, insurance, savings tools, donation platforms, and digital solutions that facilitate financial access, including interoperable systems for cross-border transactions and payment infrastructure.',
 'Validated', 'Services', 'Sum',
 ARRAY['Racial Equity'], 'Output'),

('RA71',
 'Floor area affected (m2)',
 'An estimated value of building floor area with better performance on energy efficiency and lower GHG emissions intensity compared to similar buildings in a specific region and timeframe.',
 'Needs Follow-Up', 'Businesses', 'Sum',
 ARRAY['Climate Change Mitigation'], 'Output'),

('RA13',
 'Funding for diverse-led organizations (CAD)',
 'The total value of financing directed to businesses or organizations led by individuals from equity-deserving or underrepresented groups. This includes capital allocated and capital mobilized to support racial equity, gender equity, and inclusive entrepreneurship.',
 'Validated', 'CAD', 'Sum',
 ARRAY['Financial Inclusion', 'Racial Equity'], 'Output'),

('RA14',
 'Funding to improve access to education (CAD)',
 'The total amount of funding deployed to improve access to education, such as scholarships, grants, or other financial supports. This includes capital directed toward lowering barriers for learners from underserved communities.',
 'Validated', 'CAD', 'Sum',
 ARRAY['Quality Education', 'Racial Equity'], 'Output'),

('RA58',
 'Gender pay gap, controlled (female:male average compensation)',
 'This KPI is a calculated value. Its value is equal to the difference between 1 and the Female to male pay ratio. The relationship between pay ratio metrics and the pay gap metrics is: female:male pay gap = 1 - female:male pay ratio.',
 'Draft', 'Businesses', 'Sum',
 ARRAY['Financial Inclusion'], 'Outcome'),

('RA9',
 'Greenhouse gas emissions avoided (tCO2e)',
 'The total estimated greenhouse gas emissions (in metric tonnes of CO2 equivalent) that were avoided as a result of the organization''s activities, products, or services. This includes energy efficiency, clean energy enablement, and alternative materials that reduce carbon footprints compared to conventional alternatives.',
 'Validated', 'tCO2e', 'Sum',
 ARRAY['Clean Energy', 'Climate Change Mitigation', 'Energy Efficiency', 'Green Buildings', 'Natural Resources Conservation', 'Sustainable Agriculture'], 'Outcome'),

('RA17',
 'Healthcare products or services provided (#)',
 'The total number of healthcare services delivered or healthcare-related products distributed by the organization. This includes consultations, interpreter-assisted visits, health technology units, or other care-enabling offerings.',
 'Validated', 'Services', 'Sum',
 ARRAY['Quality Health Care'], 'Output'),

('RA16',
 'Healthcare professionals engaged in providing access to or quality of health care services (#)',
 'The number of healthcare professionals actively involved in efforts to expand or improve healthcare access or quality through the organization''s interventions. This includes clinical users of technology, service placements, or capacity-building engagements.',
 'Validated', 'Healthcare professionals', 'Sum',
 ARRAY['Quality Health Care'], 'Output'),

('RA68',
 'Hospital visits avoided (#)',
 'An estimated number of unique patient hospitalisations avoided per year due to the positive impact of a company''s products and services.',
 'Needs Follow-Up', 'People', 'Sum',
 ARRAY['Quality Health Care'], 'Output'),

('RA84',
 'Increase in economic output, country (CAD)',
 'An estimated value of the increased economic output at the country level, of financial inclusion. Access to finance is widely reported to increase economic growth.',
 'Draft', 'CAD', 'Sum',
 ARRAY['Financial Inclusion'], 'Outcome'),

('RA41',
 'Increase in individual or household financial health and wealth (CAD)',
 'This indicator captures the total dollar value of improvements in financial health and wealth for individuals or households supported by the organization. It aggregates realized financial gains such as income growth, savings accumulation, or cost savings resulting from the use of products, services, or programs during the reporting period. To measure tangible progress in economic well-being among beneficiaries, particularly those from underserved or marginalized communities.',
 'Validated', 'CAD', 'Sum',
 ARRAY['Financial Inclusion'], 'Outcome'),

('RA6',
 'Individuals engaged in circular and sustainable consumption (#)',
 'The number of individuals who adopted circular or sustainable consumption behaviors through engagement with offerings such as resale, rental, styling services, fit technology, and returns diversion. This includes consumers who use services that extend product life (e.g., rental or resale platforms); individuals supported to make more sustainable choices; and users of tools or services that reduce consumption-related waste.',
 'Validated', 'Consumers', 'Sum',
 ARRAY['Pollution Prevention'], 'Outcome'),

('RA20',
 'Individuals provided with access to affordable housing (#)',
 'Number of individuals who gained access to affordable housing — including those housed directly by the organization or referred through partners (e.g., refugee support, women''s shelters, or housing networks).',
 'Validated', 'People', 'Sum',
 ARRAY['Affordable Housing'], 'Outcome'),

('RA22',
 'Individuals provided with access to employment or entrepreneurship (#)',
 'Total number of individuals who gained employment or self-employment opportunities — either through direct hiring, contract or freelance work, entrepreneurial support, or as a result of an enabling intervention (e.g., capital, platform access, or technology deployment). Includes individuals placed in jobs, supported as founders or producers, or hired as a result of product/service growth.',
 'Validated', 'People', 'Sum',
 ARRAY['Financial Inclusion', 'Quality Jobs', 'Racial Equity', 'Smallholder Agriculture'], 'Outcome'),

('RA23',
 'Individuals provided with access to energy (#)',
 'Total number of individuals who gained new or improved access to reliable, affordable, and sustainable energy services (e.g., electricity, clean cooking, solar home systems, mini-grids, or renewable-powered solutions) as a result of the organization''s products, services, or infrastructure investments during the reporting period.',
 'Validated', 'People', 'Sum',
 ARRAY['Energy Access'], 'Outcome'),

('RA24',
 'Individuals provided with access to health care (#)',
 'The number of unique individuals who gained new or ongoing access to healthcare services — either directly (e.g., through treatment, telemedicine, or integrated care programs) or indirectly (e.g., through innovations expanding reach in underserved communities) — as a result of the organization''s activities during the reporting period.',
 'Validated', 'People', 'Sum',
 ARRAY['Arts and Culture', 'Quality Health Care'], 'Outcome'),

('RA44',
 'Individuals provided with access to secure and healthy food (#)',
 'This indicator tracks the number of individuals who have gained improved access to secure, sufficient, and nutritious food as a result of the organization''s programs, services, or investments. It reflects progress in addressing food insecurity and improving dietary quality, particularly for underserved or vulnerable populations.',
 'Validated', 'People', 'Sum',
 ARRAY['Food Security'], 'Outcome'),

('RA25',
 'Individuals provided with access to water, sanitation and/or hygiene (WASH) services (#)',
 'The number of unique individuals who were provided with access to water, sanitation, and/or hygiene (WASH) services as a result of the organization''s activities during the reporting period. This includes access to clean drinking water, improved sanitation facilities, handwashing stations, hygiene education programs, and related infrastructure or services.',
 'Validated', 'People', 'Sum',
 ARRAY['Sustainable Water Management', 'Water, Sanitation, and Hygiene'], 'Outcome'),

('RA26',
 'Individuals provided with financial inclusion products or services (#)',
 'The number of unique individuals who accessed financial inclusion products or services — such as savings accounts, loans, financial education, or digital tools — through the organization''s activities during the reporting period. This includes individuals from historically excluded or underserved populations (e.g., Indigenous people, refugees, low-income communities) who gained access to services designed to improve financial security and economic participation.',
 'Validated', 'People', 'Sum',
 ARRAY['Financial Inclusion'], 'Output'),

('RA21',
 'Individuals supported through education, training or learning programs (#)',
 'The total number of individuals who accessed education, skills training, or learning support during the reporting period. This includes formal and informal programs across all age groups, such as school enrollment, vocational training, literacy initiatives, and digital education. The KPI reflects efforts to improve access to quality learning opportunities and support long-term educational and employment outcomes.',
 'Validated', 'People', 'Sum',
 ARRAY['Quality Education'], 'Output'),

('RA27',
 'Individuals with improved health outcomes (#)',
 'The number of individuals who experienced a measurable improvement in their health status, condition management, or overall well-being due to the organization''s interventions during the reporting period. This includes improvements in clinical outcomes, functional health, quality of life, or self-reported health improvements resulting from direct treatment, prevention, or health innovation — particularly among equity-deserving or underserved populations.',
 'Validated', 'People', 'Sum',
 ARRAY['Quality Health Care'], 'Impact'),

('RA79',
 'Industrial research and development enabled (CAD)',
 'The estimated annual value of industrial research and development enabled through a company''s products and services.',
 'Needs Follow-Up', 'CAD', 'Sum',
 ARRAY['Under Consideration'], 'Output'),

('RA82',
 'Installed energy or electricity capacity for sale (MW)',
 'The maximum generating capacity of power plants and other installations owned/operated by the company that use renewable and/or non-renewable energy sources to produce energy/electricity for sale. Includes renewable and non-renewable energy sources.',
 'Validated', 'MW', 'Sum',
 ARRAY['Clean Energy'], 'Output'),

('RA56',
 'Investment in research & development (CAD)',
 'The total amount of capital invested in research and development activities during the reporting period to advance product development, innovation, or technological improvement.',
 'Needs Follow-Up', 'CAD', 'Sum',
 ARRAY['Other'], 'Output'),

('RA18',
 'Land conserved, rehabilitated or restored (ha)',
 'Total area of land (in hectares) that was protected, restored, or improved in ecological value due to the organization''s activities.',
 'Validated', 'Hectares', 'Sum',
 ARRAY['Biodiversity and Ecosystem Conservation', 'Sustainable Land Management', 'Sustainable Water Management'], 'Outcome'),

('RA19',
 'Land managed with sustainable practices (ha)',
 'The total area of land actively managed by the organization or its partners using environmentally sustainable practices that improve or preserve ecosystem health, biodiversity, and/or soil quality. This includes practices such as regenerative agriculture, organic farming, sustainable forestry, climate-smart grazing, and agroforestry.',
 'Validated', 'Hectares', 'Sum',
 ARRAY['Sustainable Agriculture', 'Sustainable Land Management'], 'Outcome'),

('RA77',
 'Lives extended (#)',
 'The number of unique lives extended per year due to the positive impacts of a company''s products and services.',
 'Needs Follow-Up', 'People', 'Sum',
 ARRAY['Quality Health Care'], 'Outcome'),

('RA38',
 'Local and equity-deserving suppliers engaged (#)',
 'Total number of suppliers engaged who are local, Indigenous-owned, or part of another equity-deserving group. This KPI captures inclusive procurement practices that contribute to local economic development, inclusivity and reconciliation.',
 'Validated', 'Suppliers', 'Sum',
 ARRAY['Racial Equity'], 'Output'),

('RA50',
 'Material production displacement (tonnes)',
 'The estimated total quantity of conventional or primary material production displaced as a result of the organization''s products, services, or interventions during the reporting period. This includes avoided production of standard industry materials due to substitution, dematerialization, reuse models, product lifespan extension, or alternative material innovation.',
 'Validated', 'Tonnes', 'Sum',
 ARRAY['Waste Management & Circularity'], 'Outcome'),

('RA30',
 'Natural resources conserved (tonnes)',
 'The total estimated mass (in metric tonnes) of natural resources that were conserved or preserved as a result of the organization''s activities during the reporting period. This includes resources such as trees, fish, minerals, or other raw materials that were spared, protected, or substituted through innovations, alternative sourcing, or conservation practices.',
 'Validated', 'Tonnes', 'Sum',
 ARRAY['Natural Resources Conservation'], 'Outcome'),

('RA61',
 'Net new jobs created (FTE positions)',
 'The net increase in full-time equivalent (FTE) employees during the reporting period. This reflects organizational employment growth after accounting for hires, separations, and changes in employment intensity.',
 'Needs Follow-Up', 'Businesses', 'Sum',
 ARRAY[]::TEXT[], 'Outcome'),

('RA55',
 'New financial institution customers acquired (Customers)',
 'The total number of new customers of financial institutions acquired during the reporting period, calculated as the net annual increase in active customers relative to the prior period.',
 'Draft', 'Customers', 'Sum',
 ARRAY['Financial Inclusion'], 'Output'),

('RA72',
 'New ICT customers, previously excluded (#)',
 'The estimated number of new customers of Information and Communications Technology (ICT) providers who were previously excluded from or without access to ICT services.',
 'Validated', 'Customers', 'Sum',
 ARRAY['Other'], 'Output'),

('RA87',
 'New products avoided (#)',
 'An estimated number of new products avoided by the company''s products and services. It is calculated using reported data, scientific facts and/or a defined theory of change for specific products and services.',
 'Needs Follow-Up', 'Businesses', 'Sum',
 ARRAY['Waste Management & Circularity'], 'Output'),

('RA65',
 'NOx emissions avoided (Tonnes)',
 'An estimated value of Nitrogen Oxides (NOx) avoided by the company''s products and services, including Nitric Oxide (NO) and Nitrogen Dioxide (NO2) most relevant to air pollution.',
 'Needs Follow-Up', 'Tonnes', 'Sum',
 ARRAY['Clean Air', 'Climate Change Mitigation'], 'Outcome'),

('RA42',
 'Nutritious and sustainable food produced (tonnes)',
 'This indicator captures the total volume of food products produced or sold by portfolio companies that contribute to responsible consumption, improved nutrition, and public benefit. It includes whole foods (e.g., produce, grains), prepared meals, and functional or fermented products with health-promoting properties.',
 'Validated', 'Tonnes', 'Sum',
 ARRAY['Food Security', 'Nutrition', 'Smallholder Agriculture', 'Sustainable Agriculture'], 'Output'),

('RA48',
 'Observations made to support environmental monitoring (#)',
 'The total number of recorded observations or data points collected through environmental monitoring activities, including community-led or technology-enabled efforts. This may include water quality measurements, illegal fishing sightings, pollution incidents, biodiversity tracking, or other environmental indicators.',
 'Validated', 'Observations', 'Sum',
 ARRAY['Water, Sanitation, and Hygiene'], 'Output'),

('RA39',
 'Ownership stake by diverse-led founders (CAD)',
 'This indicator measures the dollar value of ownership in portfolio companies held by founders or co-founders from equity-deserving groups.',
 'Validated', 'CAD', 'Sum',
 ARRAY['Racial Equity'], 'Output'),

('RA73',
 'Passenger distance travelled (passenger-km)',
 'An estimated value of passenger distance traveled with green transport technologies, enabled by the company''s products and services.',
 'Needs Follow-Up', 'Businesses', 'Sum',
 ARRAY['Clean Energy'], 'Output'),

('RA76',
 'Patients receiving healthcare treatment (#)',
 'The number of unique patients that received treatment. For the purpose of this KPI, treatment is defined as the coordination or management of health care and related services among health care providers or by a health care provider with a third party. It also includes consultation between health care providers regarding a patient or the referral of a patient from one health care provider to another.',
 'Validated', 'People', 'Sum',
 ARRAY['Quality Health Care'], 'Output'),

('RA67',
 'PM2.5 emissions avoided (Tonnes)',
 'An estimated value of PM2.5 (Particulate Matter with a diameter of less than 2.5mm) avoided by the company''s products and services, relevant to air pollution.',
 'Needs Follow-Up', 'Tonnes', 'Sum',
 ARRAY['Clean Air', 'Climate Change Mitigation'], 'Output'),

('RA28',
 'Projects that supported Indigenous organizations or communities (#)',
 'The total number of projects or initiatives during the reporting period that involved meaningful collaboration with, support for, or benefit to Indigenous organizations or communities. This includes projects that were co-designed or implemented with Indigenous partners, served First Nations, Inuit, or Métis communities, or were led by Indigenous organizations.',
 'Validated', 'Projects', 'Sum',
 ARRAY['Racial Equity'], 'Output'),

('RA7',
 'Reduction in health care costs (CAD)',
 'The estimated reduction in public or private healthcare system expenditures resulting from the organization''s services or innovations. This may include avoided treatment costs, hospitalization, or improved efficiency through preventative care or digital delivery.',
 'Validated', 'CAD', 'Sum',
 ARRAY['Quality Health Care'], 'Outcome'),

('RA57',
 'Renewable electricity consumed (MWh)',
 'The total amount of renewable electricity consumed or purchased during the reporting period, including on-site generation and renewable energy certificates (RECs), measured in megawatt-hours (MWh).',
 'Validated', 'MWh', 'Sum',
 ARRAY['Clean Energy'], 'Output'),

('RA83',
 'Renewable energy or electricity production enabled (MWh)',
 'An estimated value of renewable energy or electricity production enabled by the company''s products and services.',
 'Validated', 'MWh', 'Sum',
 ARRAY['Clean Energy'], 'Output'),

('RA43',
 'Revenue generated by local food businesses and farmers (CAD)',
 'This indicator captures the total revenue generated by local food producers, processors, and suppliers that are supported directly or indirectly by the organization''s programs, investments, or procurement activities. It includes sales from farm operations, food products developed in shared infrastructure (e.g., incubators or commercial kitchens), and purchases made by the organization from regional suppliers.',
 'Validated', 'CAD', 'Sum',
 ARRAY['Smallholder Agriculture', 'Sustainable Agriculture'], 'Output'),

('RA29',
 'Revenue generated by sustainable offerings (CAD)',
 'The total revenue generated from the sale of products or services that contribute to environmental sustainability. This includes offerings that reduce environmental impact, improve resource efficiency, lower carbon emissions, or enable sustainable behavior across sectors. Revenue may come from clean tech products, low-emission manufacturing solutions, circular economy services, or sustainable consumer offerings.',
 'Validated', 'CAD', 'Sum',
 ARRAY['Climate Change Mitigation', 'Other'], 'Output'),

('RA15',
 'Scope 1 and 2 greenhouse gas emissions (tCO2e)',
 'The total amount of greenhouse gas (GHG) emissions generated by the organization during the reporting period, measured in metric tonnes of CO2 equivalent. Includes both Scope 1 (direct) and Scope 2 (indirect from energy use) emissions.',
 'Validated', 'tCO2e', 'Sum',
 ARRAY['Climate Change Mitigation'], 'Outcome'),

('RA75',
 'Scope 1, 2, and 3 greenhouse gas emissions (tCO2e)',
 'The total amount of greenhouse gas (GHG) emissions generated by the organization during the reporting period, measured in metric tonnes of CO2 equivalent, including Scope 1 (direct emissions), Scope 2 (indirect emissions from purchased energy), and Scope 3 (all other indirect emissions across the value chain).',
 'Needs Follow-Up', 'tCO2e', 'Sum',
 ARRAY['Climate Change Mitigation'], 'Outcome'),

('RA69',
 'Sick days avoided (#)',
 'Number of work sick days avoided per year due to the positive impacts of the company''s products and services.',
 'Needs Follow-Up', 'Businesses', 'Sum',
 ARRAY['Quality Health Care', 'Quality Jobs'], 'Outcome'),

('RA46',
 'Small businesses and organizations supported through capital, infrastructure or services (#)',
 'This indicator measures the number of small businesses, emerging enterprises, and nonprofit organizations that received meaningful support during the reporting period through financial capital, access to infrastructure, or operational services. Support may include financing, co-ownership models, subsidized use of production or office space, shared equipment, or tailored technical assistance that enables growth, sustainability, or improved service delivery.',
 'Validated', 'Businesses', 'Sum',
 ARRAY['Affordable Housing', 'Quality Jobs', 'Racial Equity', 'Smallholder Agriculture'], 'Output'),

('RA66',
 'SO2 emissions avoided (Tonnes)',
 'The estimated value of Sulfur Dioxide (SO2) avoided by the company''s products and services relevant to air pollution.',
 'Needs Follow-Up', 'Tonnes', 'Sum',
 ARRAY['Clean Air', 'Climate Change Mitigation'], 'Outcome'),

('RA51',
 'Species loss avoided (species.year)',
 'The estimated reduction in biodiversity loss, expressed in species.year, attributable to the organization''s products, services, or interventions relative to a defined reference scenario. This KPI reflects avoided impacts on species richness at regional or global scale, including effects from reduced land-use change, habitat degradation, or climate-related pressures.',
 'Needs Follow-Up', 'Businesses', 'Sum',
 ARRAY['Biodiversity and Ecosystem Conservation'], 'Outcome'),

('RA78',
 'Students enrolled in education programs (#)',
 'The number of students or learners enrolled in an education program as of the end of the reporting period, both full-time and part-time, where each discrete student is counted regardless of number of courses.',
 'Validated', 'People', 'Sum',
 ARRAY['Quality Education'], 'Output'),

('RA64',
 'Students graduating (#)',
 'The total number of students or learners who successfully graduated, completed a program, or achieved defined learning outcomes during the reporting period. This includes formal academic graduation as well as verified completion of vocational, technical, or alternative learning pathways.',
 'Validated', 'People', 'Sum',
 ARRAY['Quality Education'], 'Outcome'),

('RA62',
 'Total case incident rate (incidents per million hours worked)',
 'The rate of recordable workplace injury and illness cases per 1,000,000 hours worked during the reporting period.',
 'Draft', 'Businesses', 'Sum',
 ARRAY['Quality Jobs'], 'Outcome'),

('RA53',
 'Total operational waste managed (tonnes)',
 'The total quantity of waste generated and managed by the organization''s operations during the reporting period, expressed in metric tonnes. This includes both waste diverted from disposal (e.g., recycling, composting, reuse, recovery) and waste directed to disposal (e.g., landfill or incineration), consistent with GRI waste reporting standards.',
 'Validated', 'Tonnes', 'Sum',
 ARRAY['Waste Management & Circularity'], 'Output'),

('RA32',
 'Transactions that support financial inclusion (CAD)',
 'The total dollar value of financial transactions processed through the organization''s platforms, services or systems, that are explicitly designed to support financially excluded or underserved populations. This includes a range of transaction types that support individuals, communities, or organizations in sending, receiving, or managing money, such as savings groups, mobile money transfers, micro-loans, peer-to-peer platforms, or other financial inclusion tools.',
 'Validated', 'CAD', 'Sum',
 ARRAY['Financial Inclusion'], 'Output'),

('RA81',
 'Value of increase in economic position of financial inclusion customers (CAD)',
 'The estimated value of the economic gains from financial inclusion for the customer, being the individual, household or business.',
 'Validated', 'CAD', 'Sum',
 ARRAY['Financial Inclusion'], 'Outcome'),

('RA33',
 'Waste avoided (items)',
 'The total number of individual items diverted from disposal — such as landfill or incineration — due to the organization''s efforts in reuse, resale, repair, or substitution. This includes avoided waste from packaging, consumer goods, returns, or single-use products that are displaced through more sustainable practices.',
 'Validated', 'Items', 'Sum',
 ARRAY['Pollution Prevention', 'Waste Management & Circularity'], 'Outcome'),

('RA34',
 'Waste avoided (tonnes)',
 'The total quantity of waste materials avoided, diverted, or recovered as a result of the organization''s products, services, or operations during the reporting period. This includes materials that were reused, recycled, upcycled, composted, or substituted to prevent landfill or incineration, measured in metric tonnes.',
 'Validated', 'Tonnes', 'Sum',
 ARRAY['Pollution Prevention', 'Sustainable Agriculture', 'Sustainable Land Management', 'Waste Management & Circularity'], 'Outcome'),

('RA35',
 'Waste generated (tonnes)',
 'The total amount of waste generated during the reporting period as a result of the organization''s operations or activities. This includes any solid, liquid, or material waste — whether landfilled, incinerated, recycled, or otherwise treated — measured in metric tonnes.',
 'Validated', 'Tonnes', 'Sum',
 ARRAY['Waste Management & Circularity'], 'Outcome'),

('RA85',
 'Water recycled (m³)',
 'Reported volume of water recycled or reused during the period.',
 'Validated', 'm3', 'Sum',
 ARRAY['Sustainable Water Management'], 'Output'),

('RA36',
 'Water saved (m3)',
 'The total volume of water conserved, saved, or recycled due to the organization''s interventions during the reporting period. This includes water saved through product use, behavior change, process efficiency, reuse systems, or resource substitution. Calculations should convert all reported water units (gallons, liters) into cubic meters for consistency.',
 'Validated', 'm3', 'Sum',
 ARRAY['Sustainable Agriculture', 'Sustainable Water Management'], 'Outcome'),

('RA70',
 'Water treated (m3)',
 'Volume of water saved by the company''s products and services.',
 'Needs Follow-Up', 'm3', 'Sum',
 ARRAY['Sustainable Water Management'], 'Output'),

('RA63',
 'Water withdrawn (m³)',
 'The total volume of water withdrawn from all sources during the reporting period, expressed in cubic meters (m³). This includes water sourced from municipal supply, groundwater, surface water, seawater, or other freshwater systems, and may be calculated as the sum of water discharged and water consumed where direct reporting is unavailable.',
 'Validated', 'm3', 'Sum',
 ARRAY['Sustainable Water Management'], 'Output');
